version: '3'
services:
  httpd:
    build:  httpd/.
    ports:
    - "80:80"
    
  tomcat:
    build:  tomcat/.
    ports:
    - "8080:8080"
  db-setup:
    build:  db-setup/.

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root

